addSbtPlugin("org.scala-js"                % "sbt-scalajs"                % "1.17.0")
addSbtPlugin("ch.epfl.scala"               % s"sbt-scalajs-bundler"       % "0.21.1")
addSbtPlugin("org.portable-scala"          % "sbt-scalajs-crossproject"   % "1.3.2")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter"              % "1.0.0-beta44")
addSbtPlugin("com.github.sbt"              % "sbt-ci-release"             % "1.8.0")
addSbtPlugin("io.github.nafg.mergify"      % "sbt-mergify-github-actions" % "0.9.0")
addSbtPlugin("org.scoverage"               % "sbt-scoverage"              % "2.2.2")
